### ISSUE TITLE
How to add connection to `icsql-connections`?

### ISSUE THREAD

**Issue by stardiviner** [plandes/icsql#1]
After I checked out `icsql-connections` docstring, I still don't understand how to add connection for SQLite, or PostgreSQL, MySQL etc. Can you add usage connection example in README?

**Comment by plandes** [comment]
Good observation.  I added a **Connections** section, which [refers](https://github.com/plandes/cisql#connecting-to-a-database) to the command line version of the program that has yet more details.  Let me know if anything else needs clarifying.  Thanks for using the tool.
